name: Dev Checks

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies using Yarn
        run: yarn install
      - name: Run ESLint with Yarn
        run: yarn run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies using Yarn
        run: yarn install
      - name: Run tests with Yarn
        run: yarn test
